name: 'Parvez & Fatima'
favicon: null
layout_spectrum: 0.8990547268185765
typography_spectrum: 0.8493005568161607
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9269323695916682
  lightness: 0.7032839686144143
  saturation: 0.34992169379256666
  rhythmicContrast: 0.15283701242879033
purpose: []
